### PR TITLE
Add explicit render to _quarto.yml

### PR DESCRIPTION
**Pull request by ravimakhija**
Related Issue: #14 

This adds an explicit render option to the `_quarto.yml` config, as documented [here](https://quarto.org/docs/websites/#render-targets). 

In particular, this excludes `CONTRIBUTING.md` when the website is rendered. This also means any new file additions should take this render config into account, and update it as needed.

### CODE REVIEW

**Comment by ravimakhija** [comment]
Also added a `README-gh-pages.md` file that (after merging) should show up as `README.md` on the `gh-pages` branch at https://github.com/datascijedi/website/tree/gh-pages.

**Comment by mine-cetinkaya-rundel** [comment]
My worry would be that it's easy to forget to add things to the explicit render. I'm not clear on why we need some of these documents to be rendered, could you clarify?

**Review by fatso-jetson — COMMENTED** [review]
Can I make a suggestion. Rather than add explicit render, why don't we tie this up with PR #20 and link the "Edit on GitHub" footer text to the CONTRIBUTING.md file? That way, people who are interested in this particular action get a briefing on how to contribute before heading over to GitHub.

**Comment by mine-cetinkaya-rundel** [comment]
I think that might be confusing @fatso-jetson, since then they would have no direct way of identifying which document to edit.

**Comment by fatso-jetson** [comment]
That's true, there would be no direct link through from specific web page to specific file on GitHub.

This suggestion of mine is really just to solve the issue that @ravimakhija highlights - that the contributing.md file is being included in the website render, but isn't actually linked anywhere on the live site.

**Comment by ravimakhija** [comment]
Hi @mine-cetinkaya-rundel, @fatso-jetson, it seems like there are multiple moving parts here, so it was tough to write a shorter response! Looking forward to your thoughts on this. 

> My worry would be that it's easy to forget to add things to the explicit render. 

I've updated the `_quarto.yml` to use glob patterns so that the default behavior according to the Quarto docs _should_ be maintained, which I believe addresses your first concern (e.g. now nothing needs to be added to make a valid input file render). To quote [the Quarto docs](https://quarto.org/docs/projects/quarto-projects.html#Render%20Targets) - "By default, all valid Quarto input files (.qmd, .ipynb, .md, .Rmd) in the project directory will be rendered, ..."

---

> I'm not clear on why we need some of these documents to be rendered, could you clarify?

I will address each file below. 

### `CONTRIBUTING.md`

The default behavior (e.g. without a render block in `_quarto.yml` is to render this markdown file as an HTML file. The behavior I was going for was to keep the CONTRIBUTING.md in the repo, so that it's available on GitHub to website contributors, but to not include it in the website. Hence, I needed to use an exception for this (the `!`). 

Unfortunately, to quote the Quarto docs again, "You can also use the prefix ! to ignore some paths in the render list. Note that in that case you need to start by specifying everything you do want to render." Hence, I could not just add the exception and call it a day, instead I had to include what should be rendered. With glob patterns, it doesn't seem like an issue anymore, though. 

### `README-gh-pages.md`

The desired behavior for this was to copy this to the build folder, and rename it to `README.md`, so that in the GitHub UI when someone selects the `gh-pages` branch, they will see this README. Note that I could not use `README.md` as the source file here, since that was already being used for the README for the `main` branch (and any other source branch that works off `main`). 

On the other hand, I would agree that this does not have to be "rendered." In my last update pushed here, I changed the approach to use a one-liner script and the `post-render` option to simply copy over and rename the file. 

This might need to be updated or might become irrelevant depending on how the deployment is done at a later point in time, but that is TBD. 

### `LICENSE.MD` AND` CODE_OF_CONDUCT.MD` 

These were already being rendered and linked at the bottom right of the website before I started working on this. Typically I have seen these files in GitHub repositories, but not usually on a user-facing website. Also, I think these files are really geared towards website contributors, whereas the website audience is more general than just website contributors. Hence, I would be OK with removing these from the website footer and adding render exceptions for these as well. What do ya'll think, does it make sense to have these linked on the website? 

---

Finally:

> Rather than add explicit render, why don't we tie this up with PR https://github.com/datascijedi/website/pull/20 and link the "Edit on GitHub" footer text to the CONTRIBUTING.md file? 

I think this was addressed, since I started this (long) response! But yes, I agree with Mine's comment that the page-specific "Edit on GitHub" would be nice. And, I would again say that rendering and linking `CONTRIBUTING.md` from the website might be misleading, since it is currently focused on website contributions rather than more general contributions to the JEDI OG.

**Review by fatso-jetson — APPROVED** [review]

**Comment by ravimakhija** [comment]
Merged, though we can always revisit if there a better approach is discovered. I think it will also be useful to merge this and ensure that GitHub displays the `gh-pages` branch README correctly. Thanks all for the feedback.

**Pull request merged**
