### PR TITLE
Homepage updates, after committee feedback

### PR DESCRIPTION
**Pull request by fatso-jetson**
I've gone through the committee feedback and updated the design accordingly:

- Moved homepage title
- Styled "Committees" on the Activities page in the same way
- Add a stylesheet for dark mode, so that the homepage text in boxes is now legible

If we get any more feedback, I will update this PR.

### CODE REVIEW

**Comment by fatso-jetson** [comment]
I've now added the following:

- responsive grid styling for homepage
- responsive iframe styling for "get-involved" page (so that the Google Form no longer requires horizontal scrolling on mobile devices)

**Review by mine-cetinkaya-rundel — APPROVED** [review]
These look good to me!

**Comment by ravimakhija** [comment]
Lots of good stuff, just some minor suggestions and ideas below.

For the home page:
- What if we just remove the the title, maybe it'd look a bit cleaner? (We have the logo there, and the name is also in the beginning of the text.)
- It would be interesting to see what it looks like if the black and white colors on the logo are inverted for dark mode, e.g. so that the logo edges don't show in dark mode. 

For the Activities page:
- The vertical line separator between the sidebar and body seems to have disappeared? 
- Have you tried using bold for "Awards Committee" and the others? I think one of the issues is that there are many paragraphs, and it would be helpful to a website visitor to quickly recognize that the inner paragraphs are one per committee. Perhaps bullet points or indentation could be nice for this too. 

For the Get involved page:
- In a desktop browser, it looks like the form now requires scrolling vertically, whereas before it displayed fully. IMO it looks/feels better if displayed completely without the iframe scroll bar. When I initially played with this, I had to use a sufficiently large height for the iframe to make it display fully, in case that helps. 

For the mobile version (I used Safari dev tools, let me know if you have any suggestions for tooling for mobile though!):
- It appears to me that the home page shows the Twitter feed before logo and initial blurb, would it be possible to switch the order to start with the logo and initial blurb? (This issue was there before your work here as well.) 
- The Google Form does seem better now, though the horizontal scroll bar is still there for me on mobile, it is only slightly scrollable though. Do you see this too? Is there a way to completely get rid of the horizontal scroll bar on mobile?

**Review by ravimakhija — COMMENTED** [review]
Review comments are in prior comment.

**Comment by fatso-jetson** [comment]
Thanks for the comments, @ravimakhija. I'll work on these and respond properly after 26th December. Happy Holidays, all!

**Comment by ravimakhija** [comment]
Awesome sounds good, enjoy the holidays!

**Comment by fatso-jetson** [comment]
Hi Ravi, 

See below for inline comments:

> Lots of good stuff, just some minor suggestions and ideas below.
> 
> For the home page:
> 
> * What if we just remove the the title, maybe it'd look a bit cleaner? (We have the logo there, and the name is also in the beginning of the text.)

This has been done. I do think it looks better.

> * It would be interesting to see what it looks like if the black and white colors on the logo are inverted for dark mode, e.g. so that the logo edges don't show in dark mode.

I can work on this once source files are located.

> For the Activities page:
> 
> * The vertical line separator between the sidebar and body seems to have disappeared?

The Activities page was set to have a floating sidebar, which doesn't have a separator. However, it was rendering as a docked sidebar because the About page sidebar had been set that way. (I think this is a bug in Quarto, whereby the first sidebar style used is applied to all sidebars, regardless of the YAML settings.) As we're no longer using a sidebar on the About page, I changed that setting to "floating" so that the Activities page sidebar would float as intended. But we can change it back. 

My preference is to float the sidebar, though, as when you are viewing the site full screen on a monitor, the docked sidebar pulls all the page content to the left. So, with a docked sidebar, we'd have the Activities page aligned left, whereas the rest of the site content is centred.

> * Have you tried using bold for "Awards Committee" and the others? I think one of the issues is that there are many paragraphs, and it would be helpful to a website visitor to quickly recognize that the inner paragraphs are one per committee. Perhaps bullet points or indentation could be nice for this too.

The committee names are set to bold, and I've now added bullet points.

> For the Get involved page:
> 
> * In a desktop browser, it looks like the form now requires scrolling vertically, whereas before it displayed fully. IMO it looks/feels better if displayed completely without the iframe scroll bar. When I initially played with this, I had to use a sufficiently large height for the iframe to make it display fully, in case that helps.

This has been fixed.
 
> For the mobile version (I used Safari dev tools, let me know if you have any suggestions for tooling for mobile though!):
> 
> * It appears to me that the home page shows the Twitter feed before logo and initial blurb, would it be possible to switch the order to start with the logo and initial blurb? (This issue was there before your work here as well.)

I played around with this but couldn't find a wholly satisfactory solution. You can move the timeline html so that it appears after the logo and blurb, but then you are left with a chunk of white space at the top of the margin, which I think looks unattractive.

The solution I propose and have implemented is to hide the timeline on mobile devices. It is currently set so that it disappears for screen sizes smaller than 600px width.

> * The Google Form does seem better now, though the horizontal scroll bar is still there for me on mobile, it is only slightly scrollable though. Do you see this too? Is there a way to completely get rid of the horizontal scroll bar on mobile?

In Chrome dev tools, the horizontal scroll bar appears for some device sizes, but not all of them. When it does appear, no important content seems to be cropped out of the initial view. I don't think we'll be able to find a solution that works for all devices, so I propose leaving as is.

A couple of other changes to note:

* I added a logo and title to the navbar. This means that whatever page someone lands on, they can see at a glance that it is the JEDI Outreach Group site. 
* I removed the "Home" link as well, as clicking the site title and logo takes users direct to the main homepage (index.qmd).

Let me know if there's anything else to do.

**Comment by fatso-jetson** [comment]
Branch is now up to date with main. Ready to deploy with your approval, @rycoley @ravimakhija.

**Comment by ravimakhija** [comment]
Thanks Brian! Just a couple minor comments:

- On a desktop browser, under "Activities", when clicking "Webinars" the content seems to shift rightward. On the other hand, the sidebar and content for the "Activities" and "Weekly newsletter" seem to stay aligned. 
- _Perhaps_ more spacing after the logo would look good, e.g. to be more consistent with the larger spaces before each heading further down. 

With that said, I think we're good to merge as is as well and can look into these points separately as well; whatever you think is best.

**Review by ravimakhija — APPROVED** [review]
As mentioned, this looks to me, just a couple comments in my last post that we can tackle now or at a later point. Thanks @fatso-jetson!

**Comment by rycoley** [comment]
This all looks good to me. Let's go ahead and deploy and see what it all looks like with the updates.

**Comment by fatso-jetson** [comment]
All done. I've addressed the two comments Ravi made, plus opened two design
issues that need looking at.

**Pull request merged**
