### PR TITLE
Tidied up stylesheets

### PR DESCRIPTION
**Pull request by fatso-jetson**
I tried to simplify the various stylesheets so that all site-wide styles are in styles.css, while theme customisations are specific to style.scss [light theme] and darkstyle.scss [dark theme].

I've also added a line to both scss docs so we can customise the link colour for accessibility. The site-wide default that was in _quarto.yml was too dark for the dark theme.

### CODE REVIEW

**Review by mine-cetinkaya-rundel — APPROVED** [review]
This looks good to me, thanks!

One question though -- Does the link color on the dark theme pass accessibility checks? Have you checked that?

**Comment by fatso-jetson** [comment]
Thanks, Mine. I haven't checked the dark theme colour for accessibility. I
used a lighter, brighter version of the light theme link colour. Is there a
particular resource I can use to check colour accessibility?

**Comment by mine-cetinkaya-rundel** [comment]
I use https://www.deque.com/axe/devtools/ as a browser extension.

**Comment by fatso-jetson** [comment]
Darkstyle link colour passes accessibility check. Lightstyle was failing the WCAG AAA Normal Text check, according to this resource: https://webaim.org/resources/contrastchecker/. Have updated to make the link text a little darker.

**Pull request merged**
